---
title: "Projects During College 💻"
page-layout: full
theme:
  light: lux
listing: 
  contents: projects/*
  type: grid
  fields: [title, image]
  grid-columns: 5
---

Throughout my time in college, I have worked on a variety of assignments and projects that have challenged me to think critically, apply my knowledge in practical settings, and develop key problem-solving skills. These projects have spanned multiple disciplines, allowing me to gain hands-on experience, collaborate with peers, and refine my ability to research, analyse, and present findings effectively.

From individual research papers to group-based projects, each assignment has contributed to my academic and professional development. Many of these tasks required not only technical expertise but also creativity, adaptability, and strong communication skills, qualities that will be invaluable as I move forward in my career.

Below, you’ll find a collection of the assignments and projects I have completed during my final year in college. Feel free to explore them to gain insight into the work I have done and the skills I have developed along the way.


#### Reflection on on ePortfolio
This ePortfolio is my last assignment at DCU. It has been an interesting task, unlike anything I have done before. I had used GitHub previously, but I had never heard of Quarto. Although it was a completely new challenge, Damien made it very easy to understand. It did take me a long time to get used to it; I made many mistakes. However, the more I used it, the easier it became as the rules of Quarto became clearer.

During the assignment, I had time to reflect on different aspects of my time in DCU. I realise that I am very interested in people, finance, and data and want to pursue a career in a finance-related field. Due to this, I will be undertaking an MSc in Quantitative Finance at UCD. This master’s will allow me to gain more knowledge in finance and how data is involved in it, as the master’s allows for a summer internship. I plan on doing an internship in a finance firm in London in a Client Solutions role, along with strategy and fundraising. It will build upon the knowledge I have gained through my internship at KKR and my final year specialism in analytics.
